CREATE DATABASE teste_campanha;
-- GRANT USAGE ON *.* TO root@localhost IDENTIFIED BY 'root'; -- senha é entre aspas mesmo
GRANT ALL PRIVILEGES ON teste_campanha.* TO root@localhost;

CREATE TABLE teste_campanha.CAMPANHA(
	IDCAMPANHA INTEGER NOT NULL AUTO_INCREMENT COMMENT 'CODIGO SEQUENCIAL QUE DIFERENCIA CADA REGISTRO DA TABELA',
	PRIMARY KEY(IDCAMPANHA),
	NOMECAMPANHA VARCHAR(255) COMMENT 'NOME DA CAMPANHA',
	IDTIMECORACAO NUMERIC NOT NULL COMMENT 'CODIGO IDENTIFICADOR DO TIME DO CORACAO',
	DATAVIGENCIA DATE NOT NULL COMMENT 'DATA DA VIGENCIA'
);

INSERT INTO teste_campanha.CAMPANHA(NOMECAMPANHA, IDTIMECORACAO, DATAVIGENCIA) VALUES('campanha1', 10, now());
INSERT INTO teste_campanha.CAMPANHA(NOMECAMPANHA, IDTIMECORACAO, DATAVIGENCIA) VALUES('campanha2', 10, now());
INSERT INTO teste_campanha.CAMPANHA(NOMECAMPANHA, IDTIMECORACAO, DATAVIGENCIA) VALUES('campanha3', 12, now());
INSERT INTO teste_campanha.CAMPANHA(NOMECAMPANHA, IDTIMECORACAO, DATAVIGENCIA) VALUES('campanha4', 13, now());

SELECT * FROM teste_campanha.CAMPANHA;

UPDATE teste_campanha.CAMPANHA SET DATAVIGENCIA = '2017-07-13';

COMMIT;